version: '3.8'

services:
  myapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./test.db:/app/test.db
    environment:
      - GIN_MODE=release
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./test.db:/data/test.db
    command: ["sqlite3", "/data/test.db"]